# Generated by Django 4.1.3 on 2022-11-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=500)),
                ('Genre', models.CharField(max_length=500)),
                ('Review', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('Favorite', models.BooleanField(default=True)),
            ],
        ),
    ]
